# coding: utf-8

"""
    Docusign Admin API

    An API for an organization administrator to manage organizations, accounts and users  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_admin.client.configuration import Configuration


class DocuSignAccountDomainModelAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address1': 'str',
        'address2': 'str',
        'city': 'str',
        'state_province': 'str',
        'country': 'str',
        'postal_code': 'str',
        'phone': 'str',
        'fax': 'str',
        'zip_plus4': 'str'
    }

    attribute_map = {
        'address1': 'Address1',
        'address2': 'Address2',
        'city': 'City',
        'state_province': 'StateProvince',
        'country': 'Country',
        'postal_code': 'PostalCode',
        'phone': 'Phone',
        'fax': 'Fax',
        'zip_plus4': 'ZipPlus4'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """DocuSignAccountDomainModelAddress - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._address1 = None
        self._address2 = None
        self._city = None
        self._state_province = None
        self._country = None
        self._postal_code = None
        self._phone = None
        self._fax = None
        self._zip_plus4 = None
        self.discriminator = None

        setattr(self, "_{}".format('address1'), kwargs.get('address1', None))
        setattr(self, "_{}".format('address2'), kwargs.get('address2', None))
        setattr(self, "_{}".format('city'), kwargs.get('city', None))
        setattr(self, "_{}".format('state_province'), kwargs.get('state_province', None))
        setattr(self, "_{}".format('country'), kwargs.get('country', None))
        setattr(self, "_{}".format('postal_code'), kwargs.get('postal_code', None))
        setattr(self, "_{}".format('phone'), kwargs.get('phone', None))
        setattr(self, "_{}".format('fax'), kwargs.get('fax', None))
        setattr(self, "_{}".format('zip_plus4'), kwargs.get('zip_plus4', None))

    @property
    def address1(self):
        """Gets the address1 of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The address1 of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._address1

    @address1.setter
    def address1(self, address1):
        """Sets the address1 of this DocuSignAccountDomainModelAddress.


        :param address1: The address1 of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._address1 = address1

    @property
    def address2(self):
        """Gets the address2 of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The address2 of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._address2

    @address2.setter
    def address2(self, address2):
        """Sets the address2 of this DocuSignAccountDomainModelAddress.


        :param address2: The address2 of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._address2 = address2

    @property
    def city(self):
        """Gets the city of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The city of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this DocuSignAccountDomainModelAddress.


        :param city: The city of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def state_province(self):
        """Gets the state_province of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The state_province of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._state_province

    @state_province.setter
    def state_province(self, state_province):
        """Sets the state_province of this DocuSignAccountDomainModelAddress.


        :param state_province: The state_province of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._state_province = state_province

    @property
    def country(self):
        """Gets the country of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The country of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this DocuSignAccountDomainModelAddress.


        :param country: The country of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def postal_code(self):
        """Gets the postal_code of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The postal_code of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this DocuSignAccountDomainModelAddress.


        :param postal_code: The postal_code of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._postal_code = postal_code

    @property
    def phone(self):
        """Gets the phone of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The phone of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this DocuSignAccountDomainModelAddress.


        :param phone: The phone of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def fax(self):
        """Gets the fax of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The fax of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._fax

    @fax.setter
    def fax(self, fax):
        """Sets the fax of this DocuSignAccountDomainModelAddress.


        :param fax: The fax of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._fax = fax

    @property
    def zip_plus4(self):
        """Gets the zip_plus4 of this DocuSignAccountDomainModelAddress.  # noqa: E501


        :return: The zip_plus4 of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :rtype: str
        """
        return self._zip_plus4

    @zip_plus4.setter
    def zip_plus4(self, zip_plus4):
        """Sets the zip_plus4 of this DocuSignAccountDomainModelAddress.


        :param zip_plus4: The zip_plus4 of this DocuSignAccountDomainModelAddress.  # noqa: E501
        :type: str
        """

        self._zip_plus4 = zip_plus4

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocuSignAccountDomainModelAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocuSignAccountDomainModelAddress):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocuSignAccountDomainModelAddress):
            return True

        return self.to_dict() != other.to_dict()
