# coding: utf-8

"""
    DocuSign Admin API

    An API for an organization administrator to manage organizations, accounts and users  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_admin.client.configuration import Configuration


class OrgReportConfigurationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_account_limit_disabled': 'bool',
        'custom_dates_enabled': 'bool',
        'enabled_report_types': 'list[int]'
    }

    attribute_map = {
        'is_account_limit_disabled': 'is_account_limit_disabled',
        'custom_dates_enabled': 'custom_dates_enabled',
        'enabled_report_types': 'enabled_report_types'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """OrgReportConfigurationResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_account_limit_disabled = None
        self._custom_dates_enabled = None
        self._enabled_report_types = None
        self.discriminator = None

        setattr(self, "_{}".format('is_account_limit_disabled'), kwargs.get('is_account_limit_disabled', None))
        setattr(self, "_{}".format('custom_dates_enabled'), kwargs.get('custom_dates_enabled', None))
        setattr(self, "_{}".format('enabled_report_types'), kwargs.get('enabled_report_types', None))

    @property
    def is_account_limit_disabled(self):
        """Gets the is_account_limit_disabled of this OrgReportConfigurationResponse.  # noqa: E501


        :return: The is_account_limit_disabled of this OrgReportConfigurationResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_account_limit_disabled

    @is_account_limit_disabled.setter
    def is_account_limit_disabled(self, is_account_limit_disabled):
        """Sets the is_account_limit_disabled of this OrgReportConfigurationResponse.


        :param is_account_limit_disabled: The is_account_limit_disabled of this OrgReportConfigurationResponse.  # noqa: E501
        :type: bool
        """

        self._is_account_limit_disabled = is_account_limit_disabled

    @property
    def custom_dates_enabled(self):
        """Gets the custom_dates_enabled of this OrgReportConfigurationResponse.  # noqa: E501


        :return: The custom_dates_enabled of this OrgReportConfigurationResponse.  # noqa: E501
        :rtype: bool
        """
        return self._custom_dates_enabled

    @custom_dates_enabled.setter
    def custom_dates_enabled(self, custom_dates_enabled):
        """Sets the custom_dates_enabled of this OrgReportConfigurationResponse.


        :param custom_dates_enabled: The custom_dates_enabled of this OrgReportConfigurationResponse.  # noqa: E501
        :type: bool
        """

        self._custom_dates_enabled = custom_dates_enabled

    @property
    def enabled_report_types(self):
        """Gets the enabled_report_types of this OrgReportConfigurationResponse.  # noqa: E501


        :return: The enabled_report_types of this OrgReportConfigurationResponse.  # noqa: E501
        :rtype: list[int]
        """
        return self._enabled_report_types

    @enabled_report_types.setter
    def enabled_report_types(self, enabled_report_types):
        """Sets the enabled_report_types of this OrgReportConfigurationResponse.


        :param enabled_report_types: The enabled_report_types of this OrgReportConfigurationResponse.  # noqa: E501
        :type: list[int]
        """

        self._enabled_report_types = enabled_report_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgReportConfigurationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgReportConfigurationResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrgReportConfigurationResponse):
            return True

        return self.to_dict() != other.to_dict()
