# coding: utf-8

"""
    DocuSign Admin API

    An API for an organization administrator to manage organizations, accounts and users  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_admin.client.configuration import Configuration


class OrganizationExportRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'accounts': 'list[OrganizationExportAccount]',
        'domains': 'list[OrganizationExportDomain]'
    }

    attribute_map = {
        'type': 'type',
        'accounts': 'accounts',
        'domains': 'domains'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """OrganizationExportRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._type = None
        self._accounts = None
        self._domains = None
        self.discriminator = None

        setattr(self, "_{}".format('type'), kwargs.get('type', None))
        setattr(self, "_{}".format('accounts'), kwargs.get('accounts', None))
        setattr(self, "_{}".format('domains'), kwargs.get('domains', None))

    @property
    def type(self):
        """Gets the type of this OrganizationExportRequest.  # noqa: E501


        :return: The type of this OrganizationExportRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this OrganizationExportRequest.


        :param type: The type of this OrganizationExportRequest.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def accounts(self):
        """Gets the accounts of this OrganizationExportRequest.  # noqa: E501


        :return: The accounts of this OrganizationExportRequest.  # noqa: E501
        :rtype: list[OrganizationExportAccount]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts):
        """Sets the accounts of this OrganizationExportRequest.


        :param accounts: The accounts of this OrganizationExportRequest.  # noqa: E501
        :type: list[OrganizationExportAccount]
        """

        self._accounts = accounts

    @property
    def domains(self):
        """Gets the domains of this OrganizationExportRequest.  # noqa: E501


        :return: The domains of this OrganizationExportRequest.  # noqa: E501
        :rtype: list[OrganizationExportDomain]
        """
        return self._domains

    @domains.setter
    def domains(self, domains):
        """Sets the domains of this OrganizationExportRequest.


        :param domains: The domains of this OrganizationExportRequest.  # noqa: E501
        :type: list[OrganizationExportDomain]
        """

        self._domains = domains

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganizationExportRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationExportRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganizationExportRequest):
            return True

        return self.to_dict() != other.to_dict()
