# coding: utf-8

"""
    DocuSign Admin API

    An API for an organization administrator to manage organizations, accounts and users  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrganizationAccountResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'external_account_id': 'int',
        'site_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'external_account_id': 'external_account_id',
        'site_id': 'site_id'
    }

    def __init__(self, id=None, name=None, external_account_id=None, site_id=None):  # noqa: E501
        """OrganizationAccountResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._external_account_id = None
        self._site_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if external_account_id is not None:
            self.external_account_id = external_account_id
        if site_id is not None:
            self.site_id = site_id

    @property
    def id(self):
        """Gets the id of this OrganizationAccountResponse.  # noqa: E501


        :return: The id of this OrganizationAccountResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrganizationAccountResponse.


        :param id: The id of this OrganizationAccountResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OrganizationAccountResponse.  # noqa: E501


        :return: The name of this OrganizationAccountResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrganizationAccountResponse.


        :param name: The name of this OrganizationAccountResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def external_account_id(self):
        """Gets the external_account_id of this OrganizationAccountResponse.  # noqa: E501


        :return: The external_account_id of this OrganizationAccountResponse.  # noqa: E501
        :rtype: int
        """
        return self._external_account_id

    @external_account_id.setter
    def external_account_id(self, external_account_id):
        """Sets the external_account_id of this OrganizationAccountResponse.


        :param external_account_id: The external_account_id of this OrganizationAccountResponse.  # noqa: E501
        :type: int
        """

        self._external_account_id = external_account_id

    @property
    def site_id(self):
        """Gets the site_id of this OrganizationAccountResponse.  # noqa: E501


        :return: The site_id of this OrganizationAccountResponse.  # noqa: E501
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        """Sets the site_id of this OrganizationAccountResponse.


        :param site_id: The site_id of this OrganizationAccountResponse.  # noqa: E501
        :type: int
        """

        self._site_id = site_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganizationAccountResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationAccountResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
