# coding: utf-8

"""
    DocuSign Admin API

    An API for an organization administrator to manage organizations, accounts and users  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_admin.client.configuration import Configuration


class OrganizationExportTaskResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'site_id': 'int',
        'url': 'str',
        'number_rows': 'int',
        'size_bytes': 'int',
        'error_details': 'OETRErrorDetails'
    }

    attribute_map = {
        'id': 'id',
        'site_id': 'site_id',
        'url': 'url',
        'number_rows': 'number_rows',
        'size_bytes': 'size_bytes',
        'error_details': 'error_details'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """OrganizationExportTaskResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._site_id = None
        self._url = None
        self._number_rows = None
        self._size_bytes = None
        self._error_details = None
        self.discriminator = None

        setattr(self, "_{}".format('id'), kwargs.get('id', None))
        setattr(self, "_{}".format('site_id'), kwargs.get('site_id', None))
        setattr(self, "_{}".format('url'), kwargs.get('url', None))
        setattr(self, "_{}".format('number_rows'), kwargs.get('number_rows', None))
        setattr(self, "_{}".format('size_bytes'), kwargs.get('size_bytes', None))
        setattr(self, "_{}".format('error_details'), kwargs.get('error_details', None))

    @property
    def id(self):
        """Gets the id of this OrganizationExportTaskResponse.  # noqa: E501


        :return: The id of this OrganizationExportTaskResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrganizationExportTaskResponse.


        :param id: The id of this OrganizationExportTaskResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def site_id(self):
        """Gets the site_id of this OrganizationExportTaskResponse.  # noqa: E501


        :return: The site_id of this OrganizationExportTaskResponse.  # noqa: E501
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        """Sets the site_id of this OrganizationExportTaskResponse.


        :param site_id: The site_id of this OrganizationExportTaskResponse.  # noqa: E501
        :type: int
        """

        self._site_id = site_id

    @property
    def url(self):
        """Gets the url of this OrganizationExportTaskResponse.  # noqa: E501


        :return: The url of this OrganizationExportTaskResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this OrganizationExportTaskResponse.


        :param url: The url of this OrganizationExportTaskResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def number_rows(self):
        """Gets the number_rows of this OrganizationExportTaskResponse.  # noqa: E501


        :return: The number_rows of this OrganizationExportTaskResponse.  # noqa: E501
        :rtype: int
        """
        return self._number_rows

    @number_rows.setter
    def number_rows(self, number_rows):
        """Sets the number_rows of this OrganizationExportTaskResponse.


        :param number_rows: The number_rows of this OrganizationExportTaskResponse.  # noqa: E501
        :type: int
        """

        self._number_rows = number_rows

    @property
    def size_bytes(self):
        """Gets the size_bytes of this OrganizationExportTaskResponse.  # noqa: E501


        :return: The size_bytes of this OrganizationExportTaskResponse.  # noqa: E501
        :rtype: int
        """
        return self._size_bytes

    @size_bytes.setter
    def size_bytes(self, size_bytes):
        """Sets the size_bytes of this OrganizationExportTaskResponse.


        :param size_bytes: The size_bytes of this OrganizationExportTaskResponse.  # noqa: E501
        :type: int
        """

        self._size_bytes = size_bytes

    @property
    def error_details(self):
        """Gets the error_details of this OrganizationExportTaskResponse.  # noqa: E501


        :return: The error_details of this OrganizationExportTaskResponse.  # noqa: E501
        :rtype: OETRErrorDetails
        """
        return self._error_details

    @error_details.setter
    def error_details(self, error_details):
        """Sets the error_details of this OrganizationExportTaskResponse.


        :param error_details: The error_details of this OrganizationExportTaskResponse.  # noqa: E501
        :type: OETRErrorDetails
        """

        self._error_details = error_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganizationExportTaskResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationExportTaskResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganizationExportTaskResponse):
            return True

        return self.to_dict() != other.to_dict()
