# coding: utf-8

"""
    Docusign Admin API

    An API for an organization administrator to manage organizations, accounts and users  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_admin.client.configuration import Configuration


class SubscriptionProvisionModelChangeEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event_date': 'datetime',
        'action': 'str',
        'trace_token': 'str'
    }

    attribute_map = {
        'event_date': 'EventDate',
        'action': 'Action',
        'trace_token': 'TraceToken'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """SubscriptionProvisionModelChangeEvent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._event_date = None
        self._action = None
        self._trace_token = None
        self.discriminator = None

        setattr(self, "_{}".format('event_date'), kwargs.get('event_date', None))
        setattr(self, "_{}".format('action'), kwargs.get('action', None))
        setattr(self, "_{}".format('trace_token'), kwargs.get('trace_token', None))

    @property
    def event_date(self):
        """Gets the event_date of this SubscriptionProvisionModelChangeEvent.  # noqa: E501


        :return: The event_date of this SubscriptionProvisionModelChangeEvent.  # noqa: E501
        :rtype: datetime
        """
        return self._event_date

    @event_date.setter
    def event_date(self, event_date):
        """Sets the event_date of this SubscriptionProvisionModelChangeEvent.


        :param event_date: The event_date of this SubscriptionProvisionModelChangeEvent.  # noqa: E501
        :type: datetime
        """

        self._event_date = event_date

    @property
    def action(self):
        """Gets the action of this SubscriptionProvisionModelChangeEvent.  # noqa: E501


        :return: The action of this SubscriptionProvisionModelChangeEvent.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this SubscriptionProvisionModelChangeEvent.


        :param action: The action of this SubscriptionProvisionModelChangeEvent.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def trace_token(self):
        """Gets the trace_token of this SubscriptionProvisionModelChangeEvent.  # noqa: E501


        :return: The trace_token of this SubscriptionProvisionModelChangeEvent.  # noqa: E501
        :rtype: str
        """
        return self._trace_token

    @trace_token.setter
    def trace_token(self, trace_token):
        """Sets the trace_token of this SubscriptionProvisionModelChangeEvent.


        :param trace_token: The trace_token of this SubscriptionProvisionModelChangeEvent.  # noqa: E501
        :type: str
        """

        self._trace_token = trace_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionProvisionModelChangeEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionProvisionModelChangeEvent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SubscriptionProvisionModelChangeEvent):
            return True

        return self.to_dict() != other.to_dict()
